site_name: Netbox Optical Documentation
site_url: https://netbox-optical.telecomcraft.com
repo_name: telecomcraft/netbox-optical
repo_url: https://github.com/telecomcraft/netbox-optical
edit_uri: edit/main/docs/
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to Light Mode
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/telecomcraft/netbox-optical
    - icon: fontawesome/brands/twitter
      link: https://www.twitter.com/thetelecomcraft
markdown_extensions:
  - admonition
nav:
  - Introduction: 'index.md'
  - Features: 'features.md'
  - Installation: 'installation.md'
  - Configuration: 'configuration.md'
  - Modeling:
    - Core Concepts: 'modeling/core_concepts.md'
    - Key Components: 'modeling/key_components.md'
    - Simplex Circuits: 'modeling/simplex_circuits.md'
    - Duplex Circuits: 'modeling/duplex_circuits.md'
    - PON Circuits: 'modeling/pon_circuits.md'
    - WDM Circuits: 'modeling/wdm_circuits.md'
  - Testing: ''
  - Reporting: ''
